services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/local/app
    environment:
      - NODE_ENV=development
      - DEV_HOST=db
    depends_on:
      - db
      - rabbitmq
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/local/app
    environment:
      - NODE_ENV=development
  scheduler-proc:
    build:
      context: ./scheduler-proc
      dockerfile: Dockerfile.prod
    container_name: scheduler-proc
    volumes:
      - ./scheduler-proc:/usr/local/app
    depends_on:
      - server
      - rabbitmq
    environment:
      - NODE_ENV=development

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  default:
    driver: bridge